### PR TITLE
Updated feed to utilize new standards, no longer presents unpublished posts

### LINKED ISSUE #16: RSS feed includes posts that have 'published: false'

### PR DESCRIPTION
**Pull request by aaunel**
Fixes #16

### CODE REVIEW

**Comment by larister** [comment]
Great stuff, thanks @aaunel!

**Comment by aron** [comment]
Hey, thanks for finally fixing this :smile:  Looking at the code, other than showing 10 rather than 5 posts, I can't see any difference between the two loops. How does this handle unpublished posts differently?

**Comment by aron** [comment]
Also small nitpick, but the path is at /feed/atom but the resource is now rss. I guess that's not a big deal if it keeps peoples readers up to date.

**Comment by aaunel** [comment]
Hey @aron, yeah this was a bit of a headache to be honest! Changes were used from https://github.com/snaptortoise/jekyll-rss-feeds/blob/master/feed.xml.

The feed is Atom (atom:) and Dublin Core (dc:) compatible, I'd consider it an atom feed since it has some tags (like `<link rel="enclosure />"`) and otherwise gracefully degrades to RSS or DC.. ? As for unpublished posts appearing, the previous version may have cached differently, I can confirm posts that were published-then-unpublished would stick around in the feed.

May also be worth noting that Issue #16 may still occur if the feed is cached by a third-party, like Google Feedburner.

**Comment by aaunel** [comment]
Worth mentioning also, I made these changes on another Jekyll site to appear correctly in Feedly, following their (limited) docs on this http://feedly.uservoice.com/knowledgebase/topics/33323-publishers-optimize-your-feeds-for-feedly.

**Comment by aron** [comment]
@aaunel ah okay, thats great thanks for the information!

**Pull request merged**
